[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Omit Next.js public environment variables from secrets scanning
  # These are intentionally included in client-side bundles
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_PROJECT_ID"
  
  # Alternative: Omit specific paths where these secrets are expected
  SECRETS_SCAN_OMIT_PATHS = ".next/**,_next/**,netlify/functions-internal/**"

# Cache headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-server-handler"
  status = 200

# Handle all other routes (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-server-handler"
  status = 200
